# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker

services:
  - docker:dind

before_script:
  - sudo docker info
  - sudo docker-compose --version
  - sudo export PATH=$PATH:/root/sonar-scanner-4.0.0.1744-linux/bin/
  - sudo sonar-scanner -v

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build:
  stage: build
  script:
    - echo "Do a build here"
    - sudo docker-compose down && sudo docker-compose up -d
    
test-sonarqube:
  stage: test
  tags:
    - test
  script:
    - echo "Do a test here"
    - sudo sonar-scanner 

test-phpunit:
  stage: test
  tags:
    - test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy-testserver:
  stage: deploy
  tags:
    - test
  script:
    - echo "Do your deploy here"

deploy-prodserver:
  stage: deploy
  tags:
    - prod
  script:
    - echo "Do your deploy here"
  when: manual